# Generated by Django 5.2.17 on 2026-09-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='category',
            new_name='allowed_category',
        ),
    ]
